### PR TITLE
Finished firebase config

### PR DESCRIPTION
**Pull request by Daniel-Heyde**
I finished the firebase config. I ended up adding all of the firebase/google pods into our pods folder. I had to override the .gitignore, so if there's some other way I should have done that, let me know and I'll fix it.

Also, I'm not sure if GoogleService-info.plist should be on github or if everyone should just have thier own copy. Its got an API key in it so some people say to leave it out.

### CODE REVIEW

**Comment by kelliebanzon** [comment]
If GoogleService-info.plist has the API key in it, it shouldn't be public on GitHub. I'm not sure if we each create our own personal plist or if we just share those internally, but don't think we should commit it here. Besides that, I'm not sure what the deal is with the rest of the Pods/ stuff, so if it looks good to @KevinKrein then I think you're good to go.

**Review by kelliebanzon — CHANGES_REQUESTED** [review]
I'm not sure whether we all need our own personal configurations or if we just share the file securely and internally, but if `GoogleService-Info.plist` has the API key in it, then it shouldn't be public on GitHub. I don't know how to fix the fact that people will be able to see it in past commits, so we need to sort that out. All I know is you're supposed to protect your API keys.

Besides that, I don't know what the deal is with all these `Pods/` things. If it looks good to @KevinKrein, then it's good with me.

**Comment by Daniel-Heyde** [comment]
I agree that API keys typically shouldn't be public. It's easy enough to get it through other means though, so I dont think we should worry about visibility in past commits. I'll remove it from this merge.
Is there a way to put GoogleService-info.plist into travis? It'll fail the build if not.

**Comment by kelliebanzon** [comment]
I understand that we can get the API key when we need it. What I meant about the past commits is our API key is still public in those past commits. Can we delete those?

As to the Travis build, why does it need that plist to build? If it just checks that the file exists and doesn't actually source anything from it, can we just commit an empty file of the same name?

**Comment by Daniel-Heyde** [comment]
I mean its easy enough for someone to pull it out of our app if they really wanted it, so I don't think its worth worrying about being visible in past commits. You're probably right with travis. let me try that.

**Review by kelliebanzon — APPROVED** [review]

**Comment by Daniel-Heyde** [comment]
Squashing and merging might hide the api key. Not sure why the build is failing this time.

**Comment by kelliebanzon** [comment]
Is it bc some of your commits are on the master branch and some are on firebaseConfig?

**Comment by Daniel-Heyde** [comment]
Force pushed to squash commits to hide api key. Build succeeded locally, so if travis works it should be good.

**Pull request merged**
